version: '3.4'

services:
  scrumpoker:
    image: github.com/georgeyord/go-scrumpoker-api:latest
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - target: 8080
        published: 8080

