version: '3.4'

services:
  # Usage: docker-compose up url-shortener-web
  url-shortener-web:
    image: github.com/georgeyord/url-shortener-web:latest
    build:
      dockerfile: Dockerfile
      context: .
      args:
        TARGET_APP:  web
    ports:
      - target: 8080
        published: 8080
  # Usage: docker-compose run url-shortener-cli
  url-shortener-cli:
    image: github.com/georgeyord/url-shortener-cli:latest
    build:
      dockerfile: Dockerfile
      context: .
      args:
        TARGET_APP:  cli

