server:
  address: localhost
  port: 8081

application:
  name: Url shortener
  asciiart:
    theme: hollywood

db:
  type: sqlite3
  path: ../data/shortener.db

kafka:
  brokers:
    - 127.0.0.1:9092
    - 127.0.0.1:9093
  topics:
    stats: url-shortener-stats
  bytes:
    min: 10e3 // 10KB
    max: 10e5 // 1MB

cmd:
  name:
    # Comment out to print default name
    # default: cosmos
