server:
  address: localhost
  port: 8081

application:
  name: Url shortener
  asciiart:
    # Choose from: https://github.com/common-nighthawk/go-figure#supported-fonts
    theme: puffy
    subtheme: puffy

logger:
  errorlevel: debug
  targets:
    - type: human
    # - type: file
    #   path: ../log/application.log

db:
  type: sqlite3
  path: ../data/shortener.db

kafka:
  brokers:
    - 127.0.0.1:9092
  writers:
    stats:
      topic: url-shortener-stats
  readers:
    stats:
      topic: url-shortener-stats
      groupId: stats-readers
  bytes:
    min: 10e3 # 10KB
    max: 10e5 # 1MB

cmd:
  helloworld:
    name:
      # Comment out to print default name
      default: cosmos
