server:
  address: localhost
  port: 8080

application:
  name: Url shortener
  asciiart:
    theme: hollywood

db:
  type: sqlite3
  path: ../data/shortener.db

cmd:
  name:
    # Comment out to print default name
    default: cosmos
